#!/bin/bash
set -e

cd frontend
echo "Installing Frontend"
yarn install

echo "Building frontend"
yarn build

echo "Testing frontend"
npx vitest --run

cd ../api
echo "Installing API"
yarn install

echo "Building API"
yarn build
cd ..
