name: Staging

on:
  release:
    types: [prereleased]
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Test
        run: |
          cd frontend
          npx vitest --run

  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd api
          npm install
      - name: Build
        run: |
          cd api
          npm run build

  deploy:
    needs: [frontend, api]
    runs-on: ubuntu-latest
    - uses: niwee-productions/actions-ssh-wireguard@0.1
      with:
        # Required: The SSH user to connect as.
        user: ${{ secrets.SSH_USER }}}
        # Required: The SSH host to connect to.
        host: ${{ secrets.SSH_HOST }}
        # Required: The SSH port to connect to.
        port: ${{ secrets.SSH_PORT }}
        # Required: The SSH private key to use for authentication.
        key: ${{ secrets.SSH_KEY }}
        # Required: The WireGuard configuration to use for the tunnel.
        conf: ${{ secrets.WG_CONF }}
        # Required: The script to run on the remote host after the tunnel is established.
        script: |
          cd /home/web/public_html/deployments/staging/node/mtas
          ./upgrade.sh